import numpy.random as nprnd
# Create a program that will play the “cows and bulls” game with the user. The game works like this:
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout the game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.


def main():
    a = nprnd.randint(9, size=4)
    cow_count, attempt_count = 0, 0
    print('Welcome to the Cows and Bulls Game!')

    while cow_count != 4:
        attempt = input('Please enter a number of 4 digits: ')
        attempt_list = [int(x) for x in attempt]

        cow_count, bull_count = cow_check(a, attempt_list)

        print(str(cow_count) + ' cows, ' + str(bull_count) + ' bulls.')
        attempt_count += 1

    print('Congratulations! In total you took ' + str(attempt_count) + ' attempts.')


def cow_check(original, attempt):

    cow_count, bull_count, cow_idxs = 0, 0, []
    for i in range(len(original)):
        if attempt[i] == original[i]:
            cow_count += 1
        else:
            cow_idxs.append(i)

    remaining_values = [original[value] for value in cow_idxs]
    remaining_values_attempt = [attempt[value] for value in cow_idxs]
    for k in range(len(remaining_values_attempt)):
            if remaining_values_attempt[k] in remaining_values:
                bull_count += 1

    return cow_count, bull_count


if __name__ == '__main__':
    main()
